"""sprint-zero-baseline

Revision ID: e2f2634ce4f7
Revises: 
Create Date: 2026-05-18 18:37:31.640911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f2634ce4f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('note_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('encrypted_blob', sa.LargeBinary(), nullable=True),
    sa.Column('nonce', sa.LargeBinary(), nullable=True),
    sa.Column('salt', sa.LargeBinary(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('payload_location', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('modified_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
